name: "\U0001F680 Feature Request - new"
description: Suggest an idea or enhancement for this project
labels: [enhancement, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        ## Reporting a bug to React Native
        
        Thank you for taking the time to report an issue for React Native, your contribution will help
        make the framework better for everyone.

        Before you continue:
        * If you're using **Expo** and you're noticing a bug, [report it here](https://github.com/expo/expo/issues).
        * If you're found a problem with our **documentation**, [report it here](https://github.com/facebook/react-native-website/issues/).
        * If you're having an issue with **Metro** (the bundler), [report it here](https://github.com/facebook/metro/issues/).
        * If you're using an external library, report the issue to the **library first**.
        * Please [search for similar issues](https://github.com/facebook/react-native/issues) in our issue tracker.

        Make sure that your issue:
        * Have a **valid reproducer** (See [How to report a bug](https://reactnative.dev/contributing/how-to-report-a-bug)).
        * Is tested against the [**latest stable**](https://github.com/facebook/react-native/releases/) of React Native.

        🚨 IMPORTANT: Due to the extreme number of bugs we receive, issues **without a reproducer** or for an [**unsupported versions**](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported) of React Native **will be closed**.
  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: "✅ Preliminary Checks"
      description: "Please confirm the following before submitting."
      options:
        - label: "I have searched [existing issues](https://github.com/credebl/platform/issues) and [pull requests](https://github.com/credebl/platform/pulls) to avoid duplicates."
          required: true
        - label: "I'm willing to create a PR for this feature (if applicable)."
          required: false

  - type: textarea
    id: problem-statement
    attributes:
      label: "🧩 Problem Statement"
      description: "Is your feature request related to a problem? Please describe it clearly."
      placeholder: "Ex: I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "💡 Proposed Solution"
      description: "A clear and concise description of what you want to happen."
      placeholder: "Ex: It would be great if [...]"
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: "🔄 Alternatives Considered"
      description: "Have you considered any alternative solutions or features?"
      placeholder: "Ex: I also thought about [...], but [...]"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "📎 Additional Context"
      description: "Add any other context, references, mockups, or screenshots here."
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ Acceptance Criteria"
      description: "List specific tasks or outcomes that define when this request is complete."
      placeholder: |
        - A new endpoint `/v1/...` is added
        - Docs updated
        - Tests written and passing
    validations:
      required: false
